'use client';

import Link from 'next/link';
import { useCallback, useEffect, useRef, useSyncExternalStore } from 'react';

import { ArrowRight } from '@/components/ui/Button';
import type { Site } from '@/lib/types';

type Particle = {
  x: number;
  y: number;
  vx: number;
  vy: number;
  tx: number;
  ty: number;
  s: number;
  h: number;
};

const REDUCED_MOTION_QUERY = '(prefers-reduced-motion: reduce)';

function subscribeToMotionPreference(onChange: () => void) {
  const media = window.matchMedia(REDUCED_MOTION_QUERY);
  media.addEventListener('change', onChange);
  return () => media.removeEventListener('change', onChange);
}

function getMotionPreference() {
  return !window.matchMedia(REDUCED_MOTION_QUERY).matches;
}

/**
 * The claim is drawn into an offscreen canvas, sampled, and rebuilt as a field
 * of particles that fly in and settle. The pointer pushes them out of place;
 * springs pull them back.
 *
 * Nothing here is decorative-only: the text also exists as a real <h1> for
 * screen readers and crawlers, and under prefers-reduced-motion (or without
 * JavaScript) that heading is all that renders.
 */
export function AssemblyHero({ site }: { site: Site }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const wrapRef = useRef<HTMLDivElement>(null);
  const motion = useSyncExternalStore(
    subscribeToMotionPreference,
    getMotionPreference,
    () => false,
  );

  const claim = site.hero.claim;

  const run = useCallback(() => {
    const canvasEl = canvasRef.current;
    const wrapEl = wrapRef.current;
    if (!canvasEl || !wrapEl) return;

    // Narrow once, then use the locals. TS cannot see through the closures.
    const canvas: HTMLCanvasElement = canvasEl;
    const wrap: HTMLElement = wrapEl;

    const context = canvas.getContext('2d');
    if (!context) return;
    const ctx: CanvasRenderingContext2D = context;

    const off = document.createElement('canvas');
    const octx = off.getContext('2d', { willReadFrequently: true });
    if (!octx) return;

    // Canvas has no access to CSS variables, so resolve the real family name
    // that next/font generated by reading it back off the document.
    const family =
      getComputedStyle(document.body).fontFamily || 'system-ui, sans-serif';

    let width = 0;
    let height = 0;
    let particles: Particle[] = [];
    let frame = 0;
    let alive = true;
    const pointer = { x: -9999, y: -9999 };

    function build() {
      if (!octx) return;
      off.width = width;
      off.height = height;
      octx.clearRect(0, 0, width, height);
      octx.fillStyle = '#fff';
      octx.textAlign = 'center';
      octx.textBaseline = 'middle';

      // Start from a scale that keeps three lines clear of the copy block,
      // then shrink until the longest line actually fits the measured width.
      const maxWidth = width * 0.86;
      let fontSize = Math.max(28, Math.min(width * 0.145, height * 0.18));
      for (let i = 0; i < 24; i += 1) {
        octx.font = `600 ${fontSize}px ${family}`;
        const widest = Math.max(...claim.map((line) => octx.measureText(line).width));
        if (widest <= maxWidth || fontSize <= 28) break;
        fontSize *= maxWidth / widest;
      }
      octx.font = `600 ${fontSize}px ${family}`;

      const lineHeight = fontSize * 0.92;
      const centre = height * 0.44;
      claim.forEach((line, index) => {
        octx.fillText(line, width / 2, centre + (index - (claim.length - 1) / 2) * lineHeight);
      });

      let data: Uint8ClampedArray;
      try {
        data = octx.getImageData(0, 0, width, height).data;
      } catch {
        return;
      }

      const step = Math.max(3, Math.round(width / 330));
      const next: Particle[] = [];
      for (let y = 0; y < height; y += step) {
        for (let x = 0; x < width; x += step) {
          if (data[(y * width + x) * 4 + 3] > 128) {
            const angle = Math.random() * Math.PI * 2;
            const radius = Math.random() * Math.max(width, height) * 0.75;
            next.push({
              x: width / 2 + Math.cos(angle) * radius,
              y: height / 2 + Math.sin(angle) * radius,
              vx: 0,
              vy: 0,
              tx: x,
              ty: y,
              s: 0.7 + Math.random() * 0.9,
              h: Math.random(),
            });
          }
        }
      }
      particles = next;
    }

    function resize() {
      const rect = wrap.getBoundingClientRect();
      const dpr = Math.min(2, window.devicePixelRatio || 1);
      width = Math.max(1, Math.round(rect.width));
      height = Math.max(1, Math.round(rect.height));
      canvas.width = width * dpr;
      canvas.height = height * dpr;
      canvas.style.width = `${width}px`;
      canvas.style.height = `${height}px`;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      build();
    }

    function tick() {
      if (!alive) return;
      frame = requestAnimationFrame(tick);
      if (!particles.length) return;

      ctx.clearRect(0, 0, width, height);
      for (const p of particles) {
        let ax = (p.tx - p.x) * 0.028;
        let ay = (p.ty - p.y) * 0.028;

        const dx = p.x - pointer.x;
        const dy = p.y - pointer.y;
        const dist2 = dx * dx + dy * dy;
        if (dist2 < 21000) {
          const force = (21000 - dist2) / 21000;
          const dist = Math.max(8, Math.sqrt(dist2));
          ax += (dx / dist) * force * 3.6;
          ay += (dy / dist) * force * 3.6;
        }

        p.vx = (p.vx + ax) * 0.86;
        p.vy = (p.vy + ay) * 0.86;
        p.x += p.vx;
        p.y += p.vy;

        const displaced = Math.min(1, Math.hypot(p.x - p.tx, p.y - p.ty) / 90);
        ctx.fillStyle =
          displaced > 0.25
            ? `rgba(77,124,254,${0.35 + displaced * 0.5})`
            : `rgba(237,238,240,${0.5 + p.h * 0.45})`;
        ctx.fillRect(p.x, p.y, p.s * 1.6, p.s * 1.6);
      }
    }

    const onPointer = (event: PointerEvent) => {
      const rect = canvas.getBoundingClientRect();
      pointer.x = event.clientX - rect.left;
      pointer.y = event.clientY - rect.top;
    };
    const onLeave = () => {
      pointer.x = -9999;
      pointer.y = -9999;
    };

    const observer = new ResizeObserver(resize);
    observer.observe(wrap);
    window.addEventListener('pointermove', onPointer, { passive: true });
    window.addEventListener('pointerleave', onLeave);

    resize();
    tick();

    return () => {
      alive = false;
      cancelAnimationFrame(frame);
      observer.disconnect();
      window.removeEventListener('pointermove', onPointer);
      window.removeEventListener('pointerleave', onLeave);
    };
  }, [claim]);

  useEffect(() => {
    if (!motion) return;
    let cleanup: (() => void) | undefined;
    const start = () => {
      cleanup = run();
    };
    // The claim is rendered with the webfont, so wait for it or the sampled
    // shapes would be the fallback face.
    if (document.fonts?.ready) void document.fonts.ready.then(start);
    else start();
    return () => cleanup?.();
  }, [motion, run]);

  return (
    <section
      aria-label="Introduction"
      className="relative flex min-h-[100svh] flex-col justify-between overflow-hidden pb-10 pt-[var(--nav-h)] sm:pb-14"
    >
      {/* ---- the field ---- */}
      <div ref={wrapRef} className="absolute inset-0" aria-hidden="true">
        <canvas ref={canvasRef} className="absolute inset-0 h-full w-full" />
        {/* Keeps stray particles from competing with the copy block. */}
        <div className="absolute inset-x-0 bottom-0 h-48 bg-gradient-to-t from-ink via-ink/85 to-transparent" />
      </div>

      {/* ---- the same words, for people and machines that do not see canvas ---- */}
      <div className="shell relative flex flex-1 items-center justify-center py-10">
        <h1
          className={
            motion
              ? 'sr-only'
              : 'text-center text-d1 font-semibold leading-[0.92] tracking-[-0.045em] text-bone'
          }
        >
          {motion ? (
            `${claim.join(' ')}. ${site.name}.`
          ) : (
            claim.map((line) => (
              <span key={line} className="block">
                {line}
              </span>
            ))
          )}
        </h1>
      </div>

      {/* ---- the standing copy ---- */}
      <div className="shell relative">
        <div className="flex flex-col gap-7 border-t border-line/[0.08] pt-7 md:flex-row md:items-end md:justify-between md:gap-12">
          <div className="max-w-[36ch]">
            <p className="text-[1.0625rem] leading-[1.5] tracking-[-0.014em] text-bone/70">
              {site.intro}
            </p>
            <p className="mt-3 font-mono text-[0.625rem] uppercase tracking-[0.2em] text-faint">
              {site.hero.rolesLine}
            </p>
          </div>

          <div className="flex shrink-0 flex-wrap items-center gap-2.5">
            <Link href="/innoshare" className="btn btn-primary group">
              Advisory
              <ArrowRight className="transition-transform duration-500 ease-premium group-hover:translate-x-1" />
            </Link>
            <Link href="/companies" className="btn btn-ghost">
              Companies
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
